server:
  port: 8081

spring:
  application:
    name: fraudService
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5434/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true